

const loginGet = (req, res) =>{
    try {
        
    } catch (error) {
        
    }
}